FROM node:22-alpine AS build

WORKDIR /build
COPY . /build

RUN npm ci
RUN npm run build

FROM node:22-alpine AS runtime

COPY --from=build /build/node_modules /app/node_modules
COPY --from=build /build/dist /app/dist
COPY --from=build /build/package.json /app/package.json
COPY --from=build /build/tsconfig.json /app/tsconfig.json

# RUN npm i -g @nestjs/cli

WORKDIR /app

ENTRYPOINT ["node", "dist/main.js"]
